export 'package:fl_component/screens/alert_screen.dart';
export 'package:fl_component/screens/animated_screen.dart';
export 'package:fl_component/screens/avatar_screen.dart';
export 'package:fl_component/screens/card_screen.dart';
export 'package:fl_component/screens/home_screen.dart';
export 'package:fl_component/screens/inputs_screen.dart';
export 'package:fl_component/screens/listview1_screen.dart';
export 'package:fl_component/screens/listview2_screen.dart';
export 'package:fl_component/screens/slider_screen.dart';